<?php

    use Magento\Framework\App\Action\Action;

    $_productCollection = $block->getLoadedProductCollection();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');

    $image = 'product_page_main_image';
    $iterator = 1;

?>

    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
        <?php foreach ($_productCollection as $_product): ?>
            <?php $productImage = $block->getImage($_product, $image); ?>
            <section id="all-product-sec<?=$_product->getSku();?>">
                <div class="container">
                    <div class="row">
                        <div class="col-md-7 text-center">
<!--                            <img src="--><?php //echo $productImage->getImageUrl(); ?><!--" class="img-responsive center-block"/>-->
                            <img src="<?php echo $block->getUrl().'pub/media/catalog/product' . $_product->getImage(); ?>" class="img-responsive center-block"/>
                        </div>
                        <div class="col-md-5 text-center">
                            <h1><?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?> <br> STARTER KIT FOR <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?></h1>

                            <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text.</p>

                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                            <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                <?php echo $block->getBlockHtml('formkey')?>
                                <button type="submit"
                                        title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                        class="btn btn-submit btn-<?=$_product->getSku();?>"><span>get started</span>
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </section>
            <?php $iterator++; ?>
        <?php endforeach; ?>

<?php if (!$block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
    {
        "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {}
        }
    }
    </script>
<?php endif; ?>
